import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <nav className="flex gap-2">
          <Link className="bg-fuchsia-700" href="/home">
            홈
          </Link>
          <Link className="bg-amber-500" href="/best">
            베스트도전
          </Link>
          <Link className="bg-amber-700" href="/challenge">
            도전만화
          </Link>
          <Link className="bg-blue-400" href="/mypage">
            마이페이지
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
